### ISSUE TITLE
[webpack-cli] Error: Cannot find module './src/lib/cockpit-po-plugin'

### ISSUE THREAD

**Issue by leo-king** [cockpit-project/starter-kit#477]
Hello，Martin，I have checked out the project in my windows 10 and put it in my webstorm.After npm install the Project,I just want to run the 'build' to make the webpack work and so I can get the dist direcotory.But something is going wrong.The webpack said **'Cannot find module './src/lib/cockpit-po-plugin'**' And I check it in the project ,There is no /lib direcotry .So my question is that Do I have to work it in a linux machine,just check out the project,install npm,install node and then make?I'm just not very familar with how to make it work in a linux environment?I'll be very appreciate if you can give me some advices!

**Comment by martinpitt** [comment]
Please use `make` to build starter-kit. This will checkout the referenced shared code from the Cockpit project. See the README for how to build and install starter-kit.

**Comment by leo-king** [comment]
Thank you!I've tried and it worked well in my centos 7.6,the&nbsp;lib&nbsp;directory&nbsp;come&nbsp;out ，aha~




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "cockpit-project/starter-kit"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年7月23日(星期五) 下午3:31
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [cockpit-project/starter-kit] [webpack-cli] Error: Cannot find module './src/lib/cockpit-po-plugin' (#477)





 
Please use make to build starter-kit. This will checkout the referenced shared code from the Cockpit project. See the README for how to build and install starter-kit.
